-- 오랜 기간 보호한 동물(2)
-- String, Date

SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS O JOIN ANIMAL_INS I
ON O.ANIMAL_ID = I.ANIMAL_ID
ORDER BY O.DATETIME-I.DATETIME DESC -- 보호 기간 = 입양 간 날짜 - 들어온 날짜
LIMIT 2; -- 두 마리 조회